name: www
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # 国际化库
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2

  get: ^4.6.5

  get_storage:

  path_provider: ^2.0.13

  decimal: ^2.3.2
  # 屏幕适配方案 https://pub.dev/packages/flutter_screenutil
  flutter_screenutil: ^5.6.1

  #dokit: ^0.8.2-nullsafety.10

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

